name: "Build Docker demo image"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Prepare binftms 
        run:
          apt-get install -y \
          qemu \
          binfmt-support \
          qemu-user-static 
      - name: Add armhf architecture to multiarch configuration
        run:
          dpkg --add-architecture armhf && \
          update-binfmts --enable     
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./demo/Dockerfile.base
          push: true
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
          tags: |
            ghcr.io/${{ github.actor }}/base_image:latest
